spring.application.name=dashboard-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/symplifica-db
spring.datasource.username=camilo
spring.datasource.password=camilo12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS para que tu Vue (vite) le pegue sin problema
server.port=8080

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:jhoanmejia2013035@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hxaidbxxganvxerd}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${FRONTEND_URL:http://localhost:5173}