spring.application.name=dashboard-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/symplifica-db
spring.datasource.username=camilo
spring.datasource.password=camilo12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS para que tu Vue (vite) le pegue sin problema
server.port=8080